name: ValueObjects CI

on: push

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v2
        with:
          configuration: phpunit.xml.dist
          args: --testdox --color=always
